# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import treasuremap.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', treasuremap.fields.LatLongField(blank=True, max_length=24)),
                ('title', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
