# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='point',
        ),
        migrations.AddField(
            model_name='properties',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='properties',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
