# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20171121_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='lat',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='properties',
            name='lon',
            field=models.TextField(default=''),
        ),
    ]
