# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20171122_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='image',
            field=models.ImageField(default='static/images/no-img.png', upload_to='static/images'),
        ),
    ]
