# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_properties_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertiesSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.TextField(default='')),
                ('lon', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='static/images/no-img.png', upload_to='static/images')),
            ],
        ),
    ]
