# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_propertiessubmit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='propertiessubmit',
            old_name='name',
            new_name='title',
        ),
    ]
