# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20171122_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.ImageField(default='properties/static/images/no-img.png', upload_to='properties/static/images'),
        ),
        migrations.AlterField(
            model_name='propertiessubmit',
            name='image',
            field=models.ImageField(default='properties/static/images/no-img.png', upload_to='properties/static/images'),
        ),
    ]
