# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20171122_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='image',
        ),
    ]
