# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_remove_properties_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='image',
            field=models.ImageField(default='properties/static/images/no-img.png', upload_to='properties/static/images'),
        ),
    ]
